name: Masscan and ShuffleDNS Installation

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 3:00 AM UTC every day
    - cron: '0 */5 * * *'


jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Masscan
      run: |
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make
#        masscan --version

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21


    - name: Install dnsX
      run: |
        go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest

    - name: Install HttpX
      run: |
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

    - name: Install ShuffleDNS
      run: |
        go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
        shuffledns -version
#    - name: Verify installations
#      run: |
#        masscan --version
#        shuffledns -version

    - name: Install sponge
      run: |
        sudo apt-get install moreutils
 
    - name: executing DNS Brute
      env:
          DISCORD: ${{ secrets.DISCORD }}
      run: |
        cd ../
        pwd
        cd biology_continues_WRecon 
        sudo apt-get install -y crunch
        crunch 1 4 abcdefghijklmnopqrstuvwxyz1234567890 > 4_chars.txt
        wget https://github.com/zzzteph/substats/raw/main/wordlists/all
        curl -s https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/combined_subdomains.txt >combined2.txt
        curl -s https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/combined_subdomains.txt > combined1.txt
        curl -s https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_huge.txt > kovo_subs.txt
        curl -s https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt -o best-dns-wordlist.txt
        curl -s https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt -o 2m-subdomains.txt
        curl -s https://wordlists-cdn.assetnote.io/data/automated/httparchive_subdomains_2024_01_28.txt -o all_subs.txt
        cat best-dns-wordlist.txt 2m-subdomains.txt 4_chars.txt all_subs.txt all combined1.txt combined2.txt kovo_subs.txt | sort -u > subdomains-assetnote-merged.txt
        cat subdomains-assetnote-merged.txt | wc -l
        ls
        chmod +x script_shd.sh
        chmod +x script_hx.sh
        ./script_shd.sh subdomains-assetnote-merged.txt verisign.com
        ./script_hx.sh verisign.com
        ls
        cat prev_output.verisign.com.txt
        rm -rf best-dns-wordlist.txt 2m-subdomains.txt 4_chars.txt all_subs.txt all combined1.txt combined2.txt kovo_subs.txt subdomains-assetnote-merged.txt

        
          
    - name: Commit and push changes
      run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Update modified files'
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
